---
title: 'Example : IVD or Lymnode'
author: "Yi"
date: "`r format(Sys.Date())`"
output:
  pdf_document:
  html_document:
editor_options:
  chunk_output_type: console
classoption: landscape
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, error = TRUE, message=FALSE, comment="", fig.width = 10, fig.height = 10)
options(knitr.kable.NA = "")
library(knitr)
library(kableExtra)
library(latex2exp)
library(mvmeta)

files.sources = list.files("simfun/")
sapply(paste0("simfun/", files.sources), source)
```

# IVD 

```{r, include=FALSE}
data <- read.csv("data-IVD.csv")


## SET SELECTION PROBABILITY p = 1, 0.9, ..., 0.1

# (p.seq <- seq(1, 0.1, -0.1))

p.seq <- c(1, 0.8, 0.6, 0.4)

## ESITMATION WHEN WE TREAT c1, c2 AS PARAMETERS

est2 <- sapply(p.seq, function(p) {
  
  ## ESTIMATES OF THE PARAMETERS
  opt2 <- dtametasa.rc(data, p, num.var = TRUE, plot.sroc = FALSE, b.interval = c(0,2))

  c(opt2$par, opt2$sauc.ci, opt2$b.ci, opt2$convergence)
  
})



## ESITMATION WHEN WE SET c1 = c2

est11 <- sapply(p.seq, function(p) {
  
  opt1 <- dtametasa.fc(data, p,  c1.sq =0.5, num.var = TRUE, plot.sroc = FALSE, b.interval = c(0,2))
  
  c(opt1$par, opt1$sauc.ci, opt1$b.ci, opt1$convergence)
  
  })


## ESITMATION WHEN WE SET c1 = 1, c2 = 0

est10 <- sapply(p.seq, function(p) {
  
  opt1 <- dtametasa.fc(data, p, c1.sq =1, num.var = TRUE, plot.sroc = FALSE, b.interval = c(0,2))
  

  c(opt1$par, opt1$sauc.ci, opt1$b.ci, opt1$convergence)
  
})


## ESITMATION WHEN WE SET c1 = 0, c2 = 1

est01 <- sapply(p.seq, function(p) {
  
  opt1 <- dtametasa.fc(data, p, c1.sq = 0, num.var = TRUE, plot.sroc = FALSE, b.interval = c(0,2))
  
  c(opt1$par, opt1$sauc.ci, opt1$b.ci, opt1$convergence)
  
})


## ALL RESULTS

colnames(est2)<- paste0("p = ", p.seq)

colnames(est11)<- paste0("p = ", p.seq)

colnames(est10)<- paste0("p = ", p.seq)

colnames(est01)<- paste0("p = ", p.seq)

```



# SROC Plot -- IVD

```{r}
# PLEASE CHOOSE ONE SAVED DATA *******


se <- data$TP/(data$TP+data$FN)
sp <- data$TN/(data$TN+data$FP)


#setEPS(width = 10, height = 10)
# postscript("ivd.eps")
# postscript("lym.eps")

par(mfrow = c(2, 2))

# col <- gray.colors(10, gamma = 1, start = 0, end = 0.8)
col <- 1:4

plot(1-sp, se, type = "p", ylim = c(0,1), xlim = c(0,1), 
     xlab = "1-specificity", ylab = "Sensitivity")
SROC.matrix2(est2[c(1:5),  ], add = TRUE, ncols = col)
legend("bottomright", 
       bty='n',
       legend = c(sprintf("p = %.2f, SAUC = %.3f", p.seq, est2[10, ])), 
       col = col, pch = 18, pt.cex = 2, cex =1.5, 
       lty = rep(1,3))
title("(a)", adj = 0, font.main = 1, cex.main = 1.7)
title(TeX("$(\\hat{c}_1, \\, \\hat{c}_2)$"), cex.main = 1.7)

      
plot(1-sp, se, type = "p", ylim = c(0,1), xlim = c(0,1), 
     xlab = "1-specificity", ylab = "Sensitivity")
SROC.matrix2(est11[c(1:5),  ], add = TRUE, ncols = col)
legend("bottomright", 
       bty='n',
       legend = c(sprintf("p = %.2f, SAUC = %.3f", p.seq, est2[10, ])), 
       col = col, pch = 18, pt.cex = 2, cex =1.5, 
       lty = rep(1,3))
title("(b)", adj = 0, font.main = 1, cex.main = 1.7)
title(TeX("$c_1 = c_2$"), cex.main = 1.7)


plot(1-sp, se, type = "p", ylim = c(0,1), xlim = c(0,1), 
     xlab = "1-specificity", ylab = "Sensitivity")
SROC.matrix2(est10[c(1:5),  ], add = TRUE, ncols = col)
legend("bottomright", 
       bty='n',
       legend = c(sprintf("p = %.2f, SAUC = %.3f", p.seq, est2[10, ])), 
       col = col, pch = 18, pt.cex = 2, cex =1.5, 
       lty = rep(1,3))
title("(c)", adj = 0, font.main = 1, cex.main = 1.7)
title(TeX("$(c_1,\\, c_2) = (1,\\, 0)$"), cex.main = 1.7)

plot(1-sp, se, type = "p", ylim = c(0,1), xlim = c(0,1), 
     xlab = "1-specificity", ylab = "Sensitivity")
SROC.matrix2(est01[c(1:5),  ], add = TRUE, ncols = col)
legend("bottomright", 
       bty='n',
       c(
                  sprintf("p = %.2f, SAUC = %.3f", p.seq, est2[10, ])), 
       col = col, pch = 18, pt.cex = 2, cex =1.5, 
       lty = rep(1,3))
title("(d)", adj = 0, font.main = 1, cex.main = 1.7)
title(TeX("$(c_1,\\, c_2) = (0,\\, 1)$"), cex.main = 1.7)

par(mfrow = c(1,1))
# dev.off()
```

# SROC estimates --IVD

```{r}


reform.est <- function(est){

# est <- est2
est.m <- round(est[c(1:9, 11:12),],3)
sauc.ci <- sprintf("%.3f (%.3f, %.3f)", est[13,], est[14,], est[15,])

tb <- cbind(p.seq, sauc.ci, t(est.m))#[, -c(8:9, 13:14, 18:19)]

colnames(tb) <- c("$p$", "SAUC (95\\%CI)",
                  "$\\mu_1$", "$\\mu_2$", "$\\tau_1$","$\\tau_2$","$\\rho$",
                  "$c_1$", "$c_2$", "$\\beta$", "$\\alpha_p$", "se", "sp"
                  )
rownames(tb) <- NULL

tb

}

tb2  <- reform.est(est2)

tb11 <- reform.est(est11)
tb10 <- reform.est(est10)
tb01 <- reform.est(est01)

tb1 <- rbind(tb2, tb11, tb10, tb01)
tb1[6:8, 8:9] <- "0.707"
tb1[10:12, 8] <- "1"
tb1[10:12, 9] <- "0"
tb1[14:16, 8] <- "0"
tb1[14:16, 9] <- "1"

tb2 <- cbind("$(c_1, c_2)$" = c("$(\\hat{c}_1, \\hat{c}_2)$", rep("", 3),
                            "$(c_1 = c_2)$", rep("",3),
                            "$(c_1 = 1)$", rep("", 3),
                            "$(c_1 = 0)$", rep("", 3)),
             tb1)

sink("tb-ivd.tex")

kbl(tb2, 
    format = "latex",
    longtable = F, 
    booktabs = T, 
    digits =2 ,
    align = "r",
    linesep = c(rep("",3), "\\addlinespace"),
    escape = FALSE,
    caption = "data-1")

sink()

```


# SAUC plot -- IVD

```{r, fig.height=5, fig.width=10}

p.seq <- seq(1, 0.1, -0.1)

## ESITMATION WHEN WE TREAT c1, c2 AS PARAMETERS

est2 <- sapply(p.seq, function(p) {
  
  ## ESTIMATES OF THE PARAMETERS
  opt2 <- dtametasa.rc(data, p, num.var = TRUE, plot.sroc = FALSE, b.interval = c(0,2))

  c(opt2$sauc.ci)
  
})



## ESITMATION WHEN WE SET c1 = c2

est11 <- sapply(p.seq, function(p) {
  
  opt1 <- dtametasa.fc(data, p,  c1.sq =0.5, num.var = TRUE, plot.sroc = FALSE, b.interval = c(0,2))
  
  c(opt1$sauc.ci)
  
  })


## ALL RESULTS

colnames(est2)<- paste0("p = ", p.seq)

colnames(est11)<- paste0("p = ", p.seq)


## Plot
# setEPS(width = 10, height = 5)
# postscript("ivd-suac.eps")

par(mfrow = c(1,2))


matplot(t(est2),ylim=c(0,1), type = "b",lty = c(1,2,2), pch=20, col = c(1, 2,2),
         ylab = "SAUC", xlab = "p", xaxt = "n")
title(TeX("$(\\hat{c}_1, \\, \\hat{c}_2)$"), cex.main = 1.7)
axis(1, at = 1:10, labels = p.seq)
title("(a)", adj = 0, font.main = 1)
abline(h=0.5, col="grey", lty=3)


matplot(t(est11),ylim=c(0,1), type = "b",lty = c(1,2,2), pch=20, col = c(1, 2,2),
         ylab = "SAUC", xlab = "p", xaxt = "n")
title(TeX("$(c_1 = c_2)$"), cex.main = 1.7)
axis(1, at = 1:10, labels = p.seq)
title("(b)", adj = 0, font.main = 1)
abline(h=0.5, col="grey", lty=3)

par(mfrow = c(1,1))

# dev.off()
```





# Lym node


```{r, include=FALSE}
data <- read.csv("data-Lymph.csv")


## SET SELECTION PROBABILITY p = 1, 0.9, ..., 0.1

# (p.seq <- seq(1, 0.1, -0.1))

p.seq <- c(1, 0.8, 0.6, 0.4)

## ESITMATION WHEN WE TREAT c1, c2 AS PARAMETERS

est2 <- sapply(p.seq, function(p) {
  
  ## ESTIMATES OF THE PARAMETERS
  opt2 <- dtametasa.rc(data, p, num.var = TRUE, plot.sroc = FALSE, b.interval = c(0,2))

  c(opt2$par, opt2$sauc.ci, opt2$b.ci, opt2$convergence)
  
})



## ESITMATION WHEN WE SET c1 = c2

est11 <- sapply(p.seq, function(p) {
  
  opt1 <- dtametasa.fc(data, p,  c1.sq =0.5, num.var = TRUE, plot.sroc = FALSE, b.interval = c(0,2))
  
  c(opt1$par, opt1$sauc.ci, opt1$b.ci, opt1$convergence)
  
  })


## ESITMATION WHEN WE SET c1 = 1, c2 = 0

est10 <- sapply(p.seq, function(p) {
  
  opt1 <- dtametasa.fc(data, p, c1.sq =1, num.var = TRUE, plot.sroc = FALSE, b.interval = c(0,2))
  

  c(opt1$par, opt1$sauc.ci, opt1$b.ci, opt1$convergence)
  
})


## ESITMATION WHEN WE SET c1 = 0, c2 = 1

est01 <- sapply(p.seq, function(p) {
  
  opt1 <- dtametasa.fc(data, p, c1.sq = 0, num.var = TRUE, plot.sroc = FALSE, b.interval = c(0,2))
  
  c(opt1$par, opt1$sauc.ci, opt1$b.ci, opt1$convergence)
  
})


## ALL RESULTS

colnames(est2)<- paste0("p = ", p.seq)

colnames(est11)<- paste0("p = ", p.seq)

colnames(est10)<- paste0("p = ", p.seq)

colnames(est01)<- paste0("p = ", p.seq)

```



# SROC Plot -- Lym

```{r}
# PLEASE CHOOSE ONE SAVED DATA *******


se <- data$TP/(data$TP+data$FN)
sp <- data$TN/(data$TN+data$FP)


#setEPS(width = 10, height = 10)
# postscript("ivd.eps")
# postscript("lym.eps")

par(mfrow = c(2, 2))

# col <- gray.colors(10, gamma = 1, start = 0, end = 0.8)
col <- 1:4

plot(1-sp, se, type = "p", ylim = c(0,1), xlim = c(0,1), 
     xlab = "1-specificity", ylab = "Sensitivity")
SROC.matrix2(est2[c(1:5),  ], add = TRUE, ncols = col)
legend("bottomright", 
       bty='n',
       legend = c(sprintf("p = %.2f, SAUC = %.3f", p.seq, est2[10, ])), 
       col = col, pch = 18, pt.cex = 2, cex =1.5, 
       lty = rep(1,3))
title("(a)", adj = 0, font.main = 1, cex.main = 1.7)
title(TeX("$(\\hat{c}_1, \\, \\hat{c}_2)$"), cex.main = 1.7)

      
plot(1-sp, se, type = "p", ylim = c(0,1), xlim = c(0,1), 
     xlab = "1-specificity", ylab = "Sensitivity")
SROC.matrix2(est11[c(1:5),  ], add = TRUE, ncols = col)
legend("bottomright", 
       bty='n',
       legend = c(sprintf("p = %.2f, SAUC = %.3f", p.seq, est2[10, ])), 
       col = col, pch = 18, pt.cex = 2, cex =1.5, 
       lty = rep(1,3))
title("(b)", adj = 0, font.main = 1, cex.main = 1.7)
title(TeX("$c_1 = c_2$"), cex.main = 1.7)


plot(1-sp, se, type = "p", ylim = c(0,1), xlim = c(0,1), 
     xlab = "1-specificity", ylab = "Sensitivity")
SROC.matrix2(est10[c(1:5),  ], add = TRUE, ncols = col)
legend("bottomright", 
       bty='n',
       legend = c(sprintf("p = %.2f, SAUC = %.3f", p.seq, est2[10, ])), 
       col = col, pch = 18, pt.cex = 2, cex =1.5, 
       lty = rep(1,3))
title("(c)", adj = 0, font.main = 1, cex.main = 1.7)
title(TeX("$(c_1,\\, c_2) = (1,\\, 0)$"), cex.main = 1.7)

plot(1-sp, se, type = "p", ylim = c(0,1), xlim = c(0,1), 
     xlab = "1-specificity", ylab = "Sensitivity")
SROC.matrix2(est01[c(1:5),  ], add = TRUE, ncols = col)
legend("bottomright", 
       bty='n',
       c(
                  sprintf("p = %.2f, SAUC = %.3f", p.seq, est2[10, ])), 
       col = col, pch = 18, pt.cex = 2, cex =1.5, 
       lty = rep(1,3))
title("(d)", adj = 0, font.main = 1, cex.main = 1.7)
title(TeX("$(c_1,\\, c_2) = (0,\\, 1)$"), cex.main = 1.7)

par(mfrow = c(1,1))
# dev.off()
```

# SROC estimates --Lym

```{r}


reform.est <- function(est){

# est <- est2
est.m <- round(est[c(1:9, 11:12),],3)
sauc.ci <- sprintf("%.3f (%.3f, %.3f)", est[13,], est[14,], est[15,])

tb <- cbind(p.seq, sauc.ci, t(est.m))#[, -c(8:9, 13:14, 18:19)]

colnames(tb) <- c("$p$", "SAUC (95\\%CI)",
                  "$\\mu_1$", "$\\mu_2$", "$\\tau_1$","$\\tau_2$","$\\rho$",
                  "$c_1$", "$c_2$", "$\\beta$", "$\\alpha_p$", "se", "sp"
                  )
rownames(tb) <- NULL

tb

}

tb2  <- reform.est(est2)

tb11 <- reform.est(est11)
tb10 <- reform.est(est10)
tb01 <- reform.est(est01)

tb1 <- rbind(tb2, tb11, tb10, tb01)
tb1[6:8, 8:9] <- "0.707"
tb1[10:12, 8] <- "1"
tb1[10:12, 9] <- "0"
tb1[14:16, 8] <- "0"
tb1[14:16, 9] <- "1"

tb2 <- cbind("$(c_1, c_2)$" = c("$(\\hat{c}_1, \\hat{c}_2)$", rep("", 3),
                            "$(c_1 = c_2)$", rep("",3),
                            "$(c_1 = 1)$", rep("", 3),
                            "$(c_1 = 0)$", rep("", 3)),
             tb1)


sink("tb-lym.tex")

kbl(tb2, 
    format = "latex",
    longtable = F, 
    booktabs = T, 
    digits =2 ,
    align = "r",
    linesep = c(rep("",3), "\\addlinespace"),
    escape = FALSE,
    caption = "data-2")

sink()

```


# SAUC plot -- Lym

```{r, fig.height=5, fig.width=10}

p.seq <- seq(1, 0.1, -0.1)

## ESITMATION WHEN WE TREAT c1, c2 AS PARAMETERS

est2 <- sapply(p.seq, function(p) {
  
  ## ESTIMATES OF THE PARAMETERS
  opt2 <- dtametasa.rc(data, p, num.var = TRUE, plot.sroc = FALSE, b.interval = c(0,2))

  c(opt2$sauc.ci)
  
})


## ESITMATION WHEN WE SET c1 = c2

est01 <- sapply(p.seq, function(p) {
  
  opt1 <- dtametasa.fc(data, p,  c1.sq =0, num.var = TRUE, plot.sroc = FALSE, b.interval = c(0,2))
  
  c(opt1$sauc.ci)
  
  })


## ALL RESULTS

colnames(est2)<- paste0("p = ", p.seq)

colnames(est01)<- paste0("p = ", p.seq)

# setEPS(width = 10, height = 5)
# postscript("lym-suac.eps")

par(mfrow = c(1,2))


matplot(t(est2),ylim=c(0,1), type = "b",lty = c(1,2,2), pch=20, col = c(1, 2,2),
        ylab = "SAUC", xlab = "p", xaxt = "n")
title(TeX("$(\\hat{c}_1, \\, \\hat{c}_2)$"), cex.main = 1.7)
axis(1, at = 1:10, labels = p.seq)
title("(a)", adj = 0, font.main = 1)
abline(h=0.5, col="grey", lty=3)


matplot(t(est01),ylim=c(0,1), type = "b",lty = c(1,2,2), pch=20, col = c(1, 2,2),
         ylab = "SAUC", xlab = "p", xaxt = "n")
title(TeX("$(c_1, c_2) = (0, 1)$"), cex.main = 1.7)
axis(1, at = 1:10, labels = p.seq)
title("(a)", adj = 0, font.main = 1)
abline(h=0.5, col="grey", lty=3)

par(mfrow = c(1,1))

# dev.off()
```







