---
title: "AUC Points"
author: "Yi"
date: "`r format(Sys.Date())`"
output:
  pdf_document:
    toc: no
    toc_depth: '5'
  html_document:
    toc: yes
    toc_depth: 5
    toc_float: yes
editor_options:
  chunk_output_type: console
#classoption: landscape
---

```{r setup, include = FALSE}
##******************************************************************************
##
## THIS FILE PRINTS SIMPLE LINE PLOTS FOR SAUC
## JUST FOR DATA CHECK
## NOT VALID SUPPLEMENTARY TABLE FORMAT
##
##******************************************************************************


library(knitr)
opts_chunk$set(echo = FALSE, warning = FALSE, error = TRUE, message=FALSE, comment="", 
               fig.pos='H', 
               fig.height=6, fig.width=12)

options(knitr.kable.NA = ".", digits = 3)

# s.rdt <- "../../scenario/scenario-t12/set-t12-c11.RData"
# dt <- "c11"
# list.n <- 1
# row.n <- 1
# par.n <- 11
# true.par.n <- 11
```

# Boxplot of sAUC, type1

```{r}
sauc.box.basic<- function(row.n){
	
	
load(s.rdt)
true <- set[[1]][row.n,11]

sauc.lg <- NULL

	for(list.n in 1:3){
		
		load(paste0(dt, "/sim_l", list.n, "_r",row.n, ".RData"))

		dim1 <- nrow(DATA)
    dim2 <- ncol(DATA)/1000
    dim(DATA) <- c(dim1,dim2,1000)
    
    sauc <- t(DATA[11,,])
    #colnames(sauc)<- c("sa2", "sa1", "bre", "mlp")
    #sauc$id <- 1:1000

    
    #sauc.l <- reshape2::melt(sauc, id.vars = c("id"))
    #sauc.l$grp <- list.n
		
    sauc.lg <- cbind(sauc.lg, sauc)

	}				
				
colnames(sauc.lg)<- c("sa2", "sa1.c","sa1.w", "bre", "mlp",
																						"sa22", "sa12.c", "sa12.w", "bre2", "mlp2",
																						"sa23", "sa13.c", "sa13.w", "bre3", "mlp3")
    
boxplot(sauc.lg, 
								notch= TRUE,
								outline = FALSE,
								col=c("grey", "grey", "white", "white", "grey"),
								at = c(1,2,3,4,5,  7,8,9,10,11,  13,14,15,16,17),
								#ylim = c(0,1),
								ylab = "SAUC",
								las = 2,
								cex = 0.5,
								names = rep(c("P.est", "P.c", "P.w", "R.O", "R.P"),3))

abline(h = true, lty=2, col=2)
title("S=30", adj=0.15, font.main = 1)
title("S=50", font.main = 1)
title("S=200", adj=0.85, font.main = 1)
}
#abline
```


# c1=c2

```{r}
setEPS(width = 10, height = 6)
postscript("sauc-c11.eps")

s.rdt <- "../../scenario/scenario-t12/set-t12-c11.RData"
dt <- "c11"

par(mfcol = c(2,3))

sauc.box.basic(1)
title(sub = "Scenario No. 1")
sauc.box.basic(2)
title(sub = "Scenario No. 2")
sauc.box.basic(3)
title(sub = "Scenario No. 3")

sauc.box.basic(4)
title(sub = "Scenario No. 4")
sauc.box.basic(5)
title(sub = "Scenario No. 5")
sauc.box.basic(6)
title(sub = "Scenario No. 6")


par(mfrow = c(1,1))

dev.off()

```


# c1=1

```{r}
setEPS(width = 10, height = 6)
postscript("sauc-c10.eps")

s.rdt <- "../../scenario/scenario-t12/set-t12-c11.RData"
dt <- "c10"

par(mfcol = c(2,3))

sauc.box.basic(1)
title(sub = "Scenario No. 1")
sauc.box.basic(2)
title(sub = "Scenario No. 2")
sauc.box.basic(3)
title(sub = "Scenario No. 3")

sauc.box.basic(4)
title(sub = "Scenario No. 4")
sauc.box.basic(5)
title(sub = "Scenario No. 5")
sauc.box.basic(6)
title(sub = "Scenario No. 6")


par(mfrow = c(1,1))

dev.off()

```


# c1=0

```{r}
setEPS(width = 10, height = 6)
postscript("sauc-c01.eps")

s.rdt <- "../../scenario/scenario-t12/set-t12-c11.RData"
dt <- "c01"

par(mfcol = c(2,3))

sauc.box.basic(1)
title(sub = "Scenario No. 1")
sauc.box.basic(2)
title(sub = "Scenario No. 2")
sauc.box.basic(3)
title(sub = "Scenario No. 3")

sauc.box.basic(4)
title(sub = "Scenario No. 4")
sauc.box.basic(5)
title(sub = "Scenario No. 5")
sauc.box.basic(6)
title(sub = "Scenario No. 6")


par(mfrow = c(1,1))

dev.off()

```
