---
title: "Appendix Table: estimates of other parameters when c11 = 1"
subtitle: "Scenario 1-4"
author: "Yi"
date: "`r format(Sys.Date())`"
output:
  pdf_document: default
  html_document: 
    toc: no
    toc_depth: 5
    toc_float: true
editor_options:
  chunk_output_type: console
classoption: landscape
---

```{r setup, include=FALSE}
##******************************************************************************
##
## THIS FILE PRINTS THE [MEDIAN and IQR] OF ALL THE PARAMETERS
##
##******************************************************************************


library(knitr)
opts_chunk$set(echo = FALSE, warning = FALSE, error = TRUE, message=FALSE, comment="",
               fig.pos = "H")
options(knitr.kable.NA = "")
library(kableExtra)

  
table.pars <- function(list.n, row.n){
  
  load(s.rdt) 

  S <- set[[list.n]][row.n, 1]

  load(paste0(dt, "/sim_l", list.n, "_r",row.n, ".RData"))

  dim1 <- nrow(DATA)
  dim2 <- ncol(DATA)/1000
    
  name.c <- colnames(DATA)[1:dim2]

  dim(DATA) <- c(dim1, dim2, 1000)

  true.par <- c(set[[list.n]][row.n, ][c(2:6, 9:10, 7)])

  med  <- apply(DATA, 1:2, function(x) median(x, na.rm = TRUE))[1:8,]
  iq25 <- apply(DATA, 1:2, function(x) quantile(x, prob =0.25, na.rm = TRUE))[1:8,]
  iq75 <- apply(DATA, 1:2, function(x) quantile(x, prob =0.75, na.rm = TRUE))[1:8,]

  X <- cbind.data.frame(true.par, 
                        med.sa2 = sprintf("%.2f [%.2f, %.2f]", med[,1], iq25[,1], iq75[,1]),
                        med.sa1.c = sprintf("%.2f [%.2f, %.2f]", med[,2], iq25[,2], iq75[,2]),
                        med.sa1.w = sprintf("%.2f [%.2f, %.2f]", med[,3], iq25[,3], iq75[,3]),
                        med.BRE = sprintf("%.2f [%.2f, %.2f]", med[,4], iq25[,4], iq75[,4]),
                       med.BRE.p= sprintf("%.2f [%.2f, %.2f]", med[,5], iq25[,5], iq75[,5]) )
  
  X[6:8,5:6] <- NA
  X[8,3:4] <- NA
  X
}
```


# Load data

```{r, echo=TRUE}
s.rdt <- "scenario/18rows/set-0.5b-all-c10.RData"
dt <- "res/DT-pkg-0.5b-all-c10/"
```


# Scenario 1

```{r, results='asis'}


longtab <- rbind(table.pars(1, 1),
            table.pars(2, 1),
            table.pars(3, 1))

PAR <- rep(c("$\\mu_1$", "$\\mu_2$", "$\\tau_1^2$", "$\\tau_2^2$", "$\\tau_{12}$", 
         "$\\beta$", "$\\alpha_{0.7}$", "$c_1^2$"),3)

S <- c(25, rep(NA, 7), 50, rep(NA,7), 200, rep(NA,7))

longtab.f <- cbind.data.frame(S = S, PAR = PAR, longtab)

rownames(longtab.f) <- NULL
colnames(longtab.f)[2:8] <- c("Par",
                              "True", 
                              "Proposed $(\\tilde{c}_1^2, \\tilde{c}_2^2)$",
                              "Proposed $(c_1^2=1)$",
                              "Proposed $(c_1^2=c_2^2)$",
                              "Reitsma$_O$",
                              "Reitsma$_P$")


#sink("supp-c10-tab2-1.tex")

kbl(longtab.f, 
    format = "latex",
    longtable = F, 
    booktabs = T, 
    digits =2,
    align = "r",
    linesep = c(rep('', 7), '\\addlinespace'),
    escape = FALSE,
    caption = "Estimates of the parameters in median with 25th and 75th enpirial quantiles
    when $c_1^2 =1,  c_2^2 = 0$")

#sink()
```

# Scenario 2

```{r, results='asis'}


longtab <- rbind(table.pars(1, 2),
            table.pars(2, 2),
            table.pars(3, 2))

PAR <- rep(c("$\\mu_1$", "$\\mu_2$", "$\\tau_1^2$", "$\\tau_2^2$", "$\\tau_{12}$", 
         "$\\beta$", "$\\alpha_{0.7}$", "$c_1^2$"),3)

S <- c(25, rep(NA, 7), 50, rep(NA,7), 200, rep(NA,7))

longtab.f <- cbind.data.frame(S = S, PAR = PAR, longtab)

rownames(longtab.f) <- NULL
colnames(longtab.f)[2:8] <- c("Par",
                              "True", 
                              "Proposed $(\\tilde{c}_1^2, \\tilde{c}_2^2)$",
                              "Proposed $(c_1^2=1)$",
                              "Proposed $(c_1^2=c_2^2)$",
                              "Reitsma$_O$",
                              "Reitsma$_P$")


  
#sink("supp-c10-tab2-2.tex")

kbl(longtab.f, 
    format = "latex",
    longtable = F, 
    booktabs = T, 
    digits =2,
    align = "r",
    linesep = c(rep('', 7), '\\addlinespace'),
    escape = FALSE,
    caption = "Estimates of the parameters in median with 25th and 75th enpirial quantiles
    when $c_1^2 = 1, c_2^2 = 0$")
#sink()

```

# Scenario 3

```{r, results='asis'}


longtab <- rbind(table.pars(1, 3),
            table.pars(2, 3),
            table.pars(3, 3))

PAR <- rep(c("$\\mu_1$", "$\\mu_2$", "$\\tau_1^2$", "$\\tau_2^2$", "$\\tau_{12}$", 
         "$\\beta$", "$\\alpha_{0.7}$", "$c_1^2$"),3)

S <- c(25, rep(NA, 7), 50, rep(NA,7), 200, rep(NA,7))

longtab.f <- cbind.data.frame(S = S, PAR = PAR, longtab)

rownames(longtab.f) <- NULL
colnames(longtab.f)[2:8] <- c("Par",
                              "True", 
                              "Proposed $(\\tilde{c}_1^2, \\tilde{c}_2^2)$",
                              "Proposed $(c_1^2=1)$",
                              "Proposed $(c_1^2=c_2^2)$",
                              "Reitsma$_O$",
                              "Reitsma$_P$")


  
#sink("supp-c10-tab2-3.tex")

kbl(longtab.f, 
    format = "latex",
    longtable = F, 
    booktabs = T, 
    digits =2,
    align = "r",
    linesep = c(rep('', 7), '\\addlinespace'),
    escape = FALSE,
    caption = "Estimates of the parameters in median with 25th and 75th enpirial quantiles
    when $c_1^2 = 1, c_2^2 = 0$")
#sink()

```


# Scenario 4

```{r, results='asis'}


longtab <- rbind(table.pars(1, 4),
            table.pars(2, 4),
            table.pars(3, 4))

PAR <- rep(c("$\\mu_1$", "$\\mu_2$", "$\\tau_1^2$", "$\\tau_2^2$", "$\\tau_{12}$", 
         "$\\beta$", "$\\alpha_{0.7}$", "$c_1^2$"),3)

S <- c(25, rep(NA, 7), 50, rep(NA,7), 200, rep(NA,7))

longtab.f <- cbind.data.frame(S = S, PAR = PAR, longtab)

rownames(longtab.f) <- NULL
colnames(longtab.f)[2:8] <- c("Par",
                              "True", 
                              "Proposed $(\\tilde{c}_1^2, \\tilde{c}_2^2)$",
                              "Proposed $(c_1^2=1)$",
                              "Proposed $(c_1^2=c_2^2)$",
                              "Reitsma$_O$",
                              "Reitsma$_P$")


  
#sink("supp-c10-tab2-4.tex")

kbl(longtab.f, 
    format = "latex",
    longtable = F, 
    booktabs = T, 
    digits =2,
    align = "r",
    linesep = c(rep('', 7), '\\addlinespace'),
    escape = FALSE,
    caption = "Estimates of the parameters in median with 25th and 75th enpirial quantiles
    when $c_1^2 = 1, c_2^2 = 0$")
#sink()

```


