---
title: "Appendix Table 6-9"
subtitle: "Estimates of other parameters when $c_1^2 = c_2^2$ for scenario 5-8"
author: "Yi"
date: "`r format(Sys.Date())`"
output:
  pdf_document: default
  html_document: 
editor_options:
  chunk_output_type: console
---

```{r setup, include=FALSE}

library(knitr)
opts_chunk$set(echo = FALSE, warning = FALSE, error = TRUE, message=FALSE, comment="",
               fig.pos = "H")
options(knitr.kable.NA = "")
library(kableExtra)



table.pars <- function(list.n, row.n){

  load(s.rdt) 

  S <- set[[list.n]][row.n, 1]

  load(paste0(dt, "/sim_l", list.n, "_r",row.n, ".RData"))

  dim1 <- nrow(DATA)
  dim2 <- ncol(DATA)/1000
    
  name.c <- colnames(DATA)[1:dim2]

  dim(DATA) <- c(dim1, dim2, 1000)

  true.par <- c(set[[list.n]][row.n, ][c(11, 2:7, 9:10)])

  med  <- apply(DATA, 1:2, function(x) median(x, na.rm = TRUE))[c(11, 1:6, 8:9),]
  iq25 <- apply(DATA, 1:2, function(x) quantile(x, prob =0.25, na.rm = TRUE))[c(11, 1:6, 8:9),]
  iq75 <- apply(DATA, 1:2, function(x) quantile(x, prob =0.75, na.rm = TRUE))[c(11, 1:6, 8:9),]

  X <- cbind.data.frame(true.par, 
                        med.sa2 = sprintf("%.3f (%.3f, %.3f)", med[,1], iq25[,1], iq75[,1]),
                        med.sa1 = sprintf("%.3f (%.3f, %.3f)", med[,2], iq25[,2], iq75[,2]),
                        med.BRE = sprintf("%.3f (%.3f, %.3f)", med[,3], iq25[,3], iq75[,3]),
                       med.BRE.p= sprintf("%.3f (%.3f, %.3f)", med[,4], iq25[,4], iq75[,4]) )
  
  conv1 <- DATA[10,1, ]
  conv2 <- DATA[10,2, ]
  conv3 <- DATA[10,3, ]
  conv4 <- DATA[10,4, ]
  
  conv.per <- c(NA, sum(conv1 %in% 0)/1000, sum(conv2 %in% 0)/1000, sum(conv3 %in% 0)/1000, sum(conv4 %in% 0)/1000)
  
  X <- rbind(X, conv.per*100)


  X[7:9,4:5] <- NA
  X[7,3] <- NA
  X
}
```

# Load data

```{r, echo=TRUE}
 
s.rdt <- "scenario/18rows/set-0.5b-all.RData"
dt <- "res/DT-pkg-0.5b-all/"
  
```


# Scenario 5

```{r, results='asis'}
PAR <- rep(c("SAUC", "$\\mu_1$", "$\\mu_2$", "$\\tau_1^2$", "$\\tau_2^2$", "$\\tau_{12}$", 
             "$c_1^2$", "$\\beta$", "$\\alpha_{0.7}$", "CR"),3)

S <- c(25, rep(NA, 9), 50, rep(NA,9), 200, rep(NA,9))


longtab <- rbind(table.pars(1, 9),
            table.pars(2, 9),
            table.pars(3, 9))

colnm <- c("$S_P$","Par","True", 
           "Proposed $({\\tilde{c}_1^2, \\tilde{c}_2^2})$",
           "Proposed $({c_1^2=c_2^2})$",
           "Reitsma$_O$", "Reitsma$_P$")
longtab.f <- cbind.data.frame(S = S, PAR = PAR, longtab)

rownames(longtab.f) <- NULL
colnames(longtab.f) <- colnm


sink("supp-c11-tab3-5.tex")

kbl(longtab.f, 
    format = "latex",
    longtable = F, 
    booktabs = T, 
    digits =3,
    align = "r",
    linesep = c(rep('', 9), '\\addlinespace'),
    escape = FALSE,
    caption = "Estimates of the parameters when $c_1^2 = c_2^2$")

sink()
```

# Scenario 6

```{r, results='asis'}

longtab <- rbind(table.pars(1, 10),
            table.pars(2, 10),
            table.pars(3, 10))


longtab.f <- cbind.data.frame(S = S, PAR = PAR, longtab)

rownames(longtab.f) <- NULL
colnames(longtab.f) <- colnm



sink("supp-c11-tab3-6.tex")

kbl(longtab.f, 
    format = "latex",
    longtable = F, 
    booktabs = T, 
    digits =3,
    align = "r",
    linesep = c(rep('', 9), '\\addlinespace'),
    escape = FALSE,
    caption = "Estimates of the parameters when $c_1^2 = c_2^2$")

sink()
```

# Scenario 7

```{r, results='asis'}

longtab <- rbind(table.pars(1, 15),
            table.pars(2, 15),
            table.pars(3, 15))


longtab.f <- cbind.data.frame(S = S, PAR = PAR, longtab)

rownames(longtab.f) <- NULL
colnames(longtab.f) <- colnm



sink("supp-c11-tab3-7.tex")

kbl(longtab.f, 
    format = "latex",
    longtable = F, 
    booktabs = T, 
    digits =3,
    align = "r",
    linesep = c(rep('', 9), '\\addlinespace'),
    escape = FALSE,
    caption = "Estimates of the parameters when $c_1^2 = c_2^2$")

sink()
```

# Scenario 8

```{r, results='asis'}

longtab <- rbind(table.pars(1, 16),
            table.pars(2, 16),
            table.pars(3, 16))


longtab.f <- cbind.data.frame(S = S, PAR = PAR, longtab)

rownames(longtab.f) <- NULL
colnames(longtab.f) <- colnm


sink("supp-c11-tab3-8.tex")

kbl(longtab.f, 
    format = "latex",
    longtable = F, 
    booktabs = T, 
    digits =3,
    align = "r",
    linesep = c(rep('', 9), '\\addlinespace'),
    escape = FALSE,
    caption = "Estimates of the parameters when $c_1^2 = c_2^2$")

sink()
```
