---
title: "Simulation of SROC based on selected and unselected studies"
subtitle: "Figure"
author: "Yi"
date: "`r format(Sys.Date())`"
output:
  pdf_document: default
  html_document:
editor_options:
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, fig.width = 10, fig.height = 10)

imput.plot <- function(s.rdt,
                       list.n, row.n, a,
                       which.plot, 
                       seed){
  # s.rdt <- s.rdt1
  load(s.rdt)
  # 
  # list.n <- 2
  # row.n <- 1
  # seed <- 123
  # a <- -0.91
  
  S <- set[[list.n]][1,1]
  conf <- set[[list.n]][row.n, 1:8]
  
  b <- set[[list.n]][row.n, 9]
  # a <- set[[list.n]][row.n, 10]

  ##
  ## PDATA -----------------------------------------------------------
  ##
  set.seed(seed)
  pdata <- sim.pdata(conf)
  
  t <- pdata$t.clnDOR
  p.a <- pnorm(a + b*t)
  p.e <- mean(p.a, na.rm = TRUE)
  
  cx <- 1
  #pcex <- 2
  
  ##
  ## SDATA ------------------------------------------------------------
  ##

  set.seed(seed)
  s.id <- sapply(1:S, function(i) rbinom(1, 1, p.a[i])) %in% c(1)
  sdata<- pdata[s.id,] 


  p.seq <- c(1, 0.9, 0.7, 0.5)
  
  pchs <- ifelse(s.id==TRUE, 1, 4)
  
if(which.plot == "sa1"){
  
  
  est <- sapply(p.seq, function(p){
  
  sa <- dtametasa.fc(sdata, 
                     p = p, 
                     brem.init = NULL, 
                     c1.sq = set[[list.n]][row.n, 7], 
                     b.init = 1, 
                     b.interval = c(0,2),
                     a.interval = c(-3, 3),
                     positive.r = TRUE)
  
  sa$par.all
  
})
  

}


if(which.plot == "sa2"){

  est <- sapply(p.seq, function(p){
    
    sa <- dtametasa.rc(sdata, 
                     p = p, 
                     brem.init = NULL, 
                     c1.sq.init = 0.5, 
                     b.init = 1, 
                     b.interval = c(0, 2),
                     a.interval = c(-3, 3),
                     positive.r = TRUE
                     )
    sa$par
    
  })
}
  
  plot(1-pdata$sp, pdata$se, 
       xlim = c(0,1), ylim = c(0,1),
       xlab = "1 - specificity",
       ylab = "Sensitivity",
       type = "p",
       cex = cx, pch = pchs)
  
  
  # legend("bottomright", legend=round(p.e, 4))

  x <- est[c(1,2,4,5),]
  SROC.matrix(x,
              ncols = 1:4,
              spoint.cex = 2.5,
              add = TRUE)

  # fit <- mvmeta::mvmeta(cbind(y1,y2),S=cbind(v1, rep(0, nrow(pdata)), v2), data=pdata, method = "ml")
  # SROC.matrix(c(fit$coefficients, fit$Psi[c(4,3)]),
  #             ncols = 5,
  #             sroc.lty = 2,
  #             spoint.cex = 2.5,
  #             add = TRUE)
  # points(1-plogis(fit$coefficients[2]), plogis(fit$coefficients[1]), col=5, cex=2, pch=19)
  # 

}

files.sources = list.files("simfun/")
sapply(paste0("simfun/", files.sources), source)
library(latex2exp)

```


```{r, echo = TRUE}
s.rdt1 <- "scenario/scenario-t12/set-t12-c11.RData"

s.rdt2 <- "scenario/scenario-t12/set-t12-c10.RData"

s.rdt3 <- "scenario/scenario-t12/set-t12-c01.RData"

list.n <- 2  # S = 50
```

\newpage 

# Figure 1 When $c_1$ and $c_2$ are estimated

```{r}
seed <- 123


# setEPS(width = 10, height = 10)
# postscript("impute-sa2.eps", encoding="Greek")


par(oma = c(4,1,1,1),
    mfcol = c(3, 3), 
    mar = c(4, 4, 3, 1))

## c1 = c2
imput.plot(s.rdt1, list.n, 1, a = -0.91,  which.plot = "sa2", seed = seed)
title(TeX("Scenario No. 1, $c_1 = c_2$"))
# title(TeX("$u_1 = 0, \\, u_2 = 1.735, \\, c_1 = c_2$"))
# title(expression(paste( c[1]==c[2], "(", mu[1],",  ",mu[2], ") = (0, 1.735), ")))

imput.plot(s.rdt1, list.n, 3, a = -1.51,  which.plot = "sa2", seed = seed)
title(TeX("Scenario No. 3, $c_1 = c_2$"))

imput.plot(s.rdt1, list.n, 5, a = -0.95, which.plot = "sa2", seed = seed)
title(TeX("Scenario No. 5, $c_1 = c_2$"))

##  c11 = 1
imput.plot(s.rdt2, list.n, 1, a = 0.1,   which.plot = "sa2", seed = seed)
title(TeX("Scenario No. 1, $(c_1, \\,  c_2) = (1, 0)$"))
# title(TeX("$u_1 = 0, \\, u_2 = 1.735, \\,c_1 = 1, \\, c_2 = 0"))

imput.plot(s.rdt2, list.n, 3, a = -1.21, which.plot = "sa2", seed = seed)
title(TeX("Scenario No. 3, $(c_1, \\,  c_2) = (1, 0)$"))
# title(TeX("$u_1 = u_2 = 1.386, \\, c_1 = 1, \\, c_2 = 0$"))

imput.plot(s.rdt2, list.n, 5, a = -2.15, which.plot = "sa2", seed = seed)
title(TeX("Scenario No. 5, $(c_1, \\,  c_2) = (1, 0)$"))
# title(TeX("$u_1 = 2.197, \\, u_2 = -0.405, \\, c_1 = 1, \\, c_2 = 0$"))


## c11 = 0
imput.plot(s.rdt3, list.n, 1, a = -1.35, which.plot = "sa2", seed = seed)
title(TeX("Scenario No. 1, $(c_1, \\,  c_2) = (0, 1)$"))
# title(TeX("$u_1 = 0, \\, u_2 = 1.735, \\, c_1 = 0, \\, c_2 = 1$"))

imput.plot(s.rdt3, list.n, 3, a = -1.05, which.plot = "sa2", seed = seed)
title(TeX("Scenario No. 3, $(c_1, \\,  c_2) = (0, 1)$"))
# title(TeX("$u_1 = u_2 = 1.386, \\, c_1 = 0, \\, c_2 = 1$"))

imput.plot(s.rdt3, list.n, 5, a =  0.95, which.plot = "sa2", seed = seed)
title(TeX("Scenario No. 5, $(c_1, \\,  c_2) = (0, 1)$"))
# title(TeX("$u_1 = 2.197, \\, u_2 = -0.405, \\, c_1 = 0, \\, c_2 = 1$"))


par(fig = c(0, 1, 0, 1), oma = c(0, 0, 0, 0), mar = c(0, 0, 0, 0), new = TRUE)
plot(0, 0, type = 'l', bty = 'n', xaxt = 'n', yaxt = 'n')

legend_order <- matrix(1:8, ncol=4, byrow = TRUE)

legend('bottom',
       legend = c(paste0("p = ", c(1, 0.9, 0.7, 0.5)), 
                  "selected studies", "unselected studies", rep("",2))[legend_order], 
       col = c(1:4, "black", "black", rep(NULL,2))[legend_order], 
       lty = c(rep(1,4), rep(0,4))[legend_order],
       pch = c(rep(18,4), 2, 4, rep(0,2))[legend_order],
       xpd = TRUE, 
       #horiz = TRUE, 
       cex = 1.2,
       pt.cex =c(rep(2,4),1,1,rep(0,2))[legend_order],
       #seg.len=1, 
       bty = 'n',
       ncol = 4)


par(mfrow = c(1,1))

# legend_order <- matrix(1:10, ncol=5, byrow = TRUE)
# 
# legend('bottom',
#        legend = c(paste0("p = ", c(1, 0.9, 0.7, 0.5, 0.3)), 
#                   "selected studies", "unselected studies", rep("",3))[legend_order], 
#        col = c(1:5, "black", "black", rep(NULL,3))[legend_order], 
#        lty = c(rep(1,5), rep(0,5))[legend_order],
#        pch = c(rep(18,5), 2, 4, rep(0,3))[legend_order],
#        xpd = TRUE, 
#        #horiz = TRUE, 
#        cex = 1.2,
#        pt.cex =c(rep(2,5),1,1,rep(0,3))[legend_order],
#        #seg.len=1, 
#        bty = 'n',
#        ncol = 5)
# 
# 
# par(mfrow = c(1,1))

# dev.off()

```


# Figure 2 When $c_1$ and $c_2$ are assigned as true values


```{r}
seed <- 123


# setEPS(width = 10, height = 11)
# postscript("sim-sa1.eps")

par(oma = c(4,1,1,1),
    mfcol = c(3, 3), 
    mar = c(4, 4, 3, 1))

## c1 = c2
imput.plot(s.rdt1, list.n, 1, a = -0.91,  which.plot = "sa1", seed = seed)
title(TeX("Scenario No. 1, $c_1 = c_2$"))

imput.plot(s.rdt1, list.n, 3, a = -1.51,  which.plot = "sa1", seed = seed)
title(TeX("Scenario No. 3, $c_1 = c_2$"))

imput.plot(s.rdt1, list.n, 5, a = -0.95, which.plot = "sa1", seed = seed)
title(TeX("Scenario No. 5, $c_1 = c_2$"))

## c11 = 1
imput.plot(s.rdt2, list.n, 1, a = 0.1,   which.plot = "sa1", seed = seed)
title(TeX("Scenario No. 1, $(c_1, \\,  c_2) = (1, 0)$"))

imput.plot(s.rdt2, list.n, 3, a = -1.21, which.plot = "sa1", seed = seed)
title(TeX("Scenario No. 3, $(c_1, \\,  c_2) = (1, 0)$"))

imput.plot(s.rdt2, list.n, 5, a = -2.15, which.plot = "sa1", seed = seed)
title(TeX("Scenario No. 5, $(c_1, \\,  c_2) = (1, 0)$"))


## c11 = 0
imput.plot(s.rdt3, list.n, 1, a = -1.35, which.plot = "sa1", seed = seed)
title(TeX("Scenario No. 1, $(c_1, \\,  c_2) = (0, 1)$"))

imput.plot(s.rdt3, list.n, 3, a = -1.05, which.plot = "sa1", seed = seed)
title(TeX("Scenario No. 3, $(c_1, \\,  c_2) = (0, 1)$"))

imput.plot(s.rdt3, list.n, 5, a =  0.95, which.plot = "sa1", seed = seed)
title(TeX("Scenario No. 5, $(c_1, \\,  c_2) = (0, 1)$"))


par(fig = c(0, 1, 0, 1), oma = c(0, 0, 0, 0), mar = c(0, 0, 0, 0), new = TRUE)
plot(0, 0, type = 'l', bty = 'n', xaxt = 'n', yaxt = 'n')

legend_order <- matrix(1:8, ncol=4, byrow = TRUE)

legend('bottom',
       legend = c(paste0("p = ", c(1, 0.9, 0.7, 0.5)), 
                  "selected studies", "unselected studies", rep("",2))[legend_order], 
       col = c(1:4, "black", "black", rep(NULL,2))[legend_order], 
       lty = c(rep(1,4), rep(0,4))[legend_order],
       pch = c(rep(18,4), 2, 4, rep(0,2))[legend_order],
       xpd = TRUE, 
       #horiz = TRUE, 
       cex = 1.5,
       pt.cex =c(rep(2,4),1,1,rep(0,2))[legend_order],
       #seg.len=1, 
       bty = 'n',
       ncol = 4)

par(mfrow = c(1,1))

# dev.off()
```

