---
title: "Main text Table 1"
subtitle: "Estimates of SAUC with CR when $c_1^2 = c_2^2$ for scenario 1-4"
author: "Yi"
date: "`r format(Sys.Date())`"
output:
  pdf_document: default
  html_document: 
editor_options:
  chunk_output_type: console
---

```{r setup, include=FALSE}

library(knitr)
library(kableExtra)

opts_chunk$set(echo = FALSE, warning = FALSE, error = TRUE, message=FALSE, comment="")

options(knitr.kable.NA = "")

## FUNCTOIN

table.sauc <- function(list.n, row.n){
 
  load(s.rdt) 

  S <- set[[list.n]][row.n, 1]

  load(paste0(dt, "/sim_l", list.n, "_r",row.n, ".RData"))

  dim1 <- nrow(DATA)
  dim2 <- ncol(DATA)/1000
  
  name.c <- colnames(DATA)[1:dim2]

  dim(DATA) <- c(dim1, dim2, 1000)

  true.par <- rep(set[[list.n]][row.n, 11], dim2)
  true.show<- c(set[[list.n]][row.n, 11], rep(NA, dim2-1))

  
  med <- apply(DATA[11, , ,drop=FALSE], 1:2, function(x) median(x, na.rm = TRUE))
  q1  <- apply(DATA[11, , ,drop=FALSE], 1:2, function(x) quantile(x, prob =0.25, na.rm = TRUE))
  q3  <- apply(DATA[11, , ,drop=FALSE], 1:2, function(x) quantile(x, prob =0.75, na.rm = TRUE))

  conv1 <- DATA[10,1, ]
  conv2 <- DATA[10,2, ]
  conv3 <- DATA[10,3, ]
  conv4 <- DATA[10,4, ]
  
  conv.per <- c(sum(conv1 %in% 0)/1000, sum(conv2 %in% 0)/1000, sum(conv3 %in% 0)/1000, sum(conv4 %in% 0)/1000)

  X <- cbind.data.frame(sauc = true.show, 
                        MedQ = sprintf("%.3f (%.3f, %.3f)", t(med), t(q1), t(q3)),
                        CR     = conv.per*100)
  

  rownames(X) <- name.c
  
  X  
}
```


# Print table

```{r, echo=TRUE}
s.rdt <- "scenario/18rows/set-0.5b-all.RData"
dt <- "res/DT-pkg-0.5b-all/"
```

\newpage 

```{r, results='asis'}
longtab <- NULL

for(row.n in c(1,2,3,4)){
  
  longtb <- cbind.data.frame(table.sauc(1, row.n),
                             table.sauc(2, row.n)[,-1],
                             table.sauc(3, row.n)[,-1])

  longtab <- rbind.data.frame(longtab, longtb)
  
}

longtab.f <- cbind.data.frame(" " = rep(c("Proposed $({\\tilde{c}_1^2, \\tilde{c}_2^2})$",
                                          "Proposed $({c_1^2=c_2^2})$",
                                          "Reitsma$_O$",
                                          "Reitsma$_P$"),4),
                              longtab)
rownames(longtab.f) <- NULL
colnames(longtab.f)[2:8] <- c("SUAC", rep(c("Median (Q1, Q3)", "CR"), 3))


sink("tb-sim-tab1.tex")

kbl(longtab.f, 
    format = "latex",
    longtable = F, 
    booktabs = T, 
    digits = 3,
    align = "r",
    linesep = c('', '', '', '\\addlinespace'),
    escape = FALSE,
    caption = "Estimates of SAUC when $c_1^2 = c_2^2$"
    ) %>% 
  add_header_above(c("","", "$S_P = 25$" = 2, "$S_P = 50$" = 2, "$S_P = 200$" = 2), escape = FALSE) %>% 
  kable_styling(latex_options = c("repeat_header"), full_width = FALSE) %>%
  footnote("Proposed $({\\tilde{c}_1^2, \\tilde{c}_2^2})$ is the proposed model estimating $(c_1^2, c_2^2)^T$;
Proposed $({\\tilde{c}_1^2, \\tilde{c}_2^2})$ is the proposed model specified $c_1^2=c_2^2 =0.5$;
Reitsma$_O$ is Reitsma model based on the observed studies;
and Reitsma$_P$ is Reitsma model based on the population studies.", escape = FALSE, threeparttable = TRUE)

sink()

```

