---
title: "Table 2. Estimates of sAUC with convergence rate when c11 = 1"
subtitle: "Scenario 1-4"
author: "Yi"
date: "`r format(Sys.Date())`"
output:
  pdf_document: default
  html_document: 
    toc: no
    toc_depth: 5
    toc_float: true
editor_options:
  chunk_output_type: console
---

```{r setup, include=FALSE}

library(knitr)
library(kableExtra)

opts_chunk$set(echo = FALSE, warning = FALSE, error = TRUE, message=FALSE, comment="")

options(knitr.kable.NA = "")

table.sauc <- function(list.n, row.n){
 
  load(s.rdt) 

  S <- set[[list.n]][row.n, 1]

  load(paste0(dt, "/sim_l", list.n, "_r",row.n, ".RData"))

  dim1 <- nrow(DATA)
  dim2 <- ncol(DATA)/1000
  
  name.c <- colnames(DATA)[1:dim2]

  dim(DATA) <- c(dim1, dim2, 1000)

  true.par <- rep(set[[list.n]][row.n, 11], dim2)
  true.show<- c(set[[list.n]][row.n, 11], rep(NA, dim2-1))

  
  med  <- apply(DATA[11, , ,drop=FALSE], 1:2, function(x) median(x, na.rm = TRUE))
  iq25 <- apply(DATA[11, , ,drop=FALSE], 1:2, function(x) quantile(x, prob =0.25, na.rm = TRUE))
  iq75 <- apply(DATA[11, , ,drop=FALSE], 1:2, function(x) quantile(x, prob =0.75, na.rm = TRUE))
  #iqr  <- iq75 - iq25
  
  conv1 <- DATA[10,1, ]
  conv2 <- DATA[10,2, ]
  conv3 <- DATA[10,3, ]
  conv4 <- DATA[10,4, ]
  conv5 <- DATA[10,5, ]

  conv.per <- c(sum(conv1 %in% 0)/1000, sum(conv2 %in% 0)/1000, sum(conv3 %in% 0)/1000, 
                sum(conv4 %in% 0)/1000, sum(conv5 %in% 0)/1000)

  X <- cbind.data.frame(sAUC = true.show, 
                        #MED    = t(med)*100, 
                        #IQR    = sprintf("[%.2f, %.2f]", t(iq25)*100, t(iq75)*100), 
                        "Median [Q$_1$, Q$_3$]" = sprintf("%.2f [%.2f, %.2f]", t(med), t(iq25), t(iq75)),
                        CR     = conv.per*100)
  

  rownames(X) <- name.c
  
  X  
}
```


# Print table

```{r, echo=TRUE}

s.rdt <- "scenario/18rows/set-0.5b-all-c10.RData"
dt <- "res/DT-pkg-0.5b-all-c10/"

```


```{r, results='asis'}
longtab <- NULL

for(row.n in c(1,2,3,4)){
  
  longtb <- cbind.data.frame(table.sauc(1, row.n),
                             table.sauc(2, row.n)[,-1],
                             table.sauc(3, row.n)[,-1])

  longtab <- rbind.data.frame(longtab, longtb)
  
}

longtab.f <- cbind.data.frame(" " = rep(c("Proposed $(\\tilde{c}_1^2, \\tilde{c}_2^2)$",
                                          "Proposed $(c_1^2=1)$",
                                          "Proposed $(c_1^2=c_2^2)$",
                                          "Reistma$_O$",
                                          "Reistma$_P$"),4),
                              longtab)
rownames(longtab.f) <- NULL
colnames(longtab.f)[3:8] <- c(paste0("Median [Q$_1$", footnote_marker_symbol(1, "latex"), 
                                     ", Q$_3$", footnote_marker_symbol(2, "latex"), "]"),
                              paste0("CR", footnote_marker_symbol(3, "latex")), 
                              rep(c("Median [Q$_1$, Q$_3$]", "CR"), 2))

# sink("Tab2.tex")

kbl(longtab.f, 
    format = "latex",
    longtable = F, 
    booktabs = T, 
    digits =2,
    align = "r",
    linesep = c('', '', '', '', '\\addlinespace'),
    escape = FALSE,
    caption = "Estimates of sAUC when ($c_1^2 = 1;  c_2^2 = 0$)") %>% 
  add_header_above(c("","", "S = 25" = 2, "S = 50" = 2, "S = 200" = 2)) %>% 
  kable_styling(latex_options = c("repeat_header"), full_width = FALSE) %>%
  footnote(symbol = c("25th empirical quartile; ", 
                      "75th empirical quartile; ",
                      "Convergence rate. "))

# sink()



```

