---
title: "Estimates of SAUC with CR, 3 True c vectors"
subtitle: "t12"
author: "Yi"
date: "`r format(Sys.Date())`"
output:
  pdf_document: default
  html_document: 
editor_options:
  chunk_output_type: console
classoption: landscape
---

```{r setup, include=FALSE}

library(knitr)
library(kableExtra)

opts_chunk$set(echo = FALSE, warning = FALSE, error = TRUE, message=FALSE, comment="")

options(knitr.kable.NA = "")

table.sauc <- function(list.n, row.n){
 
  load(s.rdt) 

  S <- set[[list.n]][row.n, 1]

  load(paste0(dt, "/sim_l", list.n, "_r",row.n, ".RData"))

  dim1 <- nrow(DATA)
  dim2 <- ncol(DATA)/1000
  
  name.c <- colnames(DATA)[1:dim2]

  dim(DATA) <- c(dim1, dim2, 1000)

  true.par <- rep(set[[list.n]][row.n, 11], dim2)
  true.show<- c(set[[list.n]][row.n, 11], rep(NA, dim2-1))

  
  med  <- apply(DATA[11, , ,drop=FALSE], 1:2, function(x) median(x, na.rm = TRUE))
  q1 <- apply(DATA[11, , ,drop=FALSE], 1:2, function(x) quantile(x, prob =0.25, na.rm = TRUE))
  q3 <- apply(DATA[11, , ,drop=FALSE], 1:2, function(x) quantile(x, prob =0.75, na.rm = TRUE))
  
  conv1 <- DATA[10,1, ]
  conv2 <- DATA[10,2, ]
  conv3 <- DATA[10,3, ]
  conv4 <- DATA[10,4, ]
  conv5 <- DATA[10,5, ]

  conv.per <- c(sum(conv1 %in% 0)/1000, sum(conv2 %in% 0)/1000, sum(conv3 %in% 0)/1000, 
                sum(conv4 %in% 0)/1000, sum(conv5 %in% 0)/1000)

  X <- cbind.data.frame(sAUC = true.show,
    med = sprintf("%.3f (%.3f, %.3f)", t(med), t(q1), t(q3)),
    CR     = conv.per*100)
  
  X[c(1,3,2,4,5),]
}
```


# Print table

```{r, echo=TRUE} 

# s.rdt <- "../../scenario/scenario-t12/set-t12-c11.RData"
# dt <- "c11"


# s.rdt <- "../../scenario/scenario-t12/set-t12-c10.RData"
# dt <- "c10"


s.rdt <- "../../scenario/scenario-t12/set-t12-c01.RData"
dt <- "c01"

```

# With No column

```{r, results='asis'}
longtab <- NULL

for(row.n in c(1:6)){
  
  longtb <- cbind.data.frame(table.sauc(1, row.n),
                             table.sauc(2, row.n)[,-1],
                             table.sauc(3, row.n)[,-1])

  longtab <- rbind.data.frame(longtab, longtb)
  
}

longtab.f <- cbind.data.frame(no = c(1, rep(NA, 4),2, rep(NA, 4),3, rep(NA, 4),4, rep(NA, 4),5, rep(NA, 4),6, rep(NA, 4) ),
                              " " = rep(c("Proposed $(\\hat{c}_1, \\hat{c}_2)$",
                                          "Proposed $(c_1 = c_2)$",
                                          "Proposed $(c_1 = 0)$",
                                          # "Proposed (correct)",
                                          # "Proposed (wrong)",
                                          "Reistma$_O$",
                                          "Reistma$_P$"),6),
                              longtab)
rownames(longtab.f) <- NULL
colnames(longtab.f) <- c("No."," ", "True", rep(c("Median (Q1, Q3)", "CR"), 3))

# sink("tb-sauc-t12-c01.tex")
# sink("tb-sauc-t12-c10.tex")
# sink("tb-sauc-t12-c11.tex")

kbl(longtab.f, 
    format = "latex",
    longtable = F, 
    booktabs = T, 
    digits = 3,
    align = "r",
    linesep = c('', '', '', '', '\\addlinespace'),
    escape = FALSE,
    caption = "Estimates of SAUC when true $c_1 = c_2$") %>% 
  add_header_above(c("","","", "$S = 25$" = 2, "$S = 50$" = 2, "$S = 200$" = 2), escape = FALSE) %>% 
  kable_styling(latex_options = c("repeat_header"), full_width = FALSE) %>%
  footnote(general = "Proposed $({hat{c}_1, hat{c}_2})$ is the proposed model estimating $(c_1, c_2)$;
   Proposed $(c_1 = c_2)$ is the proposed model correctly specifying that $c_1=c_2$;
   Proposed $(c_1 = 1)$ is the proposed model misspecifying that $(c_1, c_2) = (1,0)$;
   Reitsma$_O$ is Reitsma model based on the observed studies;
   and Reitsma$_P$ is Reitsma model based on the population studies.", escape = FALSE, threeparttable = TRUE)


# sink()



```

# Without No column

```{r, results='asis', include=FALSE}
longtab <- NULL

for(row.n in c(1:6)){
  
  longtb <- cbind.data.frame(table.sauc(1, row.n),
                             table.sauc(2, row.n)[,-1],
                             table.sauc(3, row.n)[,-1])

  longtab <- rbind.data.frame(longtab, longtb)
  
}

longtab.f <- cbind.data.frame(
                              " " = rep(c("Proposed $(\\hat{c}_1, \\hat{c}_2)$",
                                          "Proposed $(c_1 = c_2)$",
                                          "Proposed $(c_1 = 1)$",
                                          "Reistma$_O$",
                                          "Reistma$_P$"),6),
                              longtab)
rownames(longtab.f) <- NULL
colnames(longtab.f) <- c(" ", "True", rep(c("Median (Q1, Q3)", "CR"), 3))


# sink("tb-sauc-11.tex")

kbl(longtab.f, 
    format = "latex",
    longtable = F, 
    booktabs = T, 
    digits = 3,
    align = "r",
    linesep = c('', '', '', '', '\\addlinespace'),
    escape = FALSE,
    caption = "Estimates of SAUC when true $c_1 = c_2$") %>% 
  add_header_above(c("","", "$S = 25$" = 2, "$S = 50$" = 2, "$S = 200$" = 2), escape = FALSE) %>% 
  kable_styling(latex_options = c("repeat_header"), full_width = FALSE) %>%
  footnote(general = "Proposed $({hat{c}_1, hat{c}_2})$ is the proposed model estimating $(c_1, c_2)$;
   Proposed $(c_1 = c_2)$ is the proposed model correctly specifying that $c_1=c_2$;
   Proposed $(c_1 = 1)$ is the proposed model misspecifying that $(c_1, c_2) = (1,0)$;
   Reitsma$_O$ is Reitsma model based on the observed studies;
   and Reitsma$_P$ is Reitsma model based on the population studies.", escape = FALSE, threeparttable = TRUE)


# sink()



```